"""Persistence repositories for canonical write access."""

from pixelpast.persistence.repositories.canonical import (
    AssetRepository,
    AssetUpsertResult,
    EventReplaceResult,
    EventRepository,
    JobRunRepository,
    PersonRepository,
    SourceRepository,
    SourceUpsertResult,
    TagRepository,
)
from pixelpast.persistence.repositories.daily_aggregates import (
    CanonicalTimelineRepository,
    DailyAggregateRepository,
    DailyAggregateSnapshot,
    DailyViewRepository,
)
from pixelpast.persistence.repositories.timeline_read import (
    DailyAggregateReadRepository,
    DailyAggregateReadSnapshot,
    DayActivityItemSnapshot,
    DayMapPointSnapshot,
    DayPersonLinkSnapshot,
    DayTagLinkSnapshot,
    DayTimelineItemSnapshot,
    DailyViewCatalogSnapshot,
    DayTimelineRepository,
    ExplorationReadRepository,
    TimelineBoundsSnapshot,
)
from pixelpast.persistence.repositories.social_graph_read import (
    PersonAssetMembershipSnapshot,
    SocialGraphLinkSnapshot,
    SocialGraphPersonSnapshot,
    SocialGraphReadRepository,
    SocialGraphReadSnapshot,
)

__all__ = [
    "AssetRepository",
    "AssetUpsertResult",
    "CanonicalTimelineRepository",
    "DayActivityItemSnapshot",
    "DayMapPointSnapshot",
    "DayPersonLinkSnapshot",
    "DayTagLinkSnapshot",
    "DailyViewCatalogSnapshot",
    "DailyAggregateReadRepository",
    "DailyAggregateReadSnapshot",
    "DailyAggregateRepository",
    "DailyAggregateSnapshot",
    "DailyViewRepository",
    "EventReplaceResult",
    "EventRepository",
    "DayTimelineItemSnapshot",
    "DayTimelineRepository",
    "ExplorationReadRepository",
    "JobRunRepository",
    "PersonRepository",
    "PersonAssetMembershipSnapshot",
    "SocialGraphLinkSnapshot",
    "SocialGraphPersonSnapshot",
    "SocialGraphReadRepository",
    "SocialGraphReadSnapshot",
    "SourceRepository",
    "SourceUpsertResult",
    "TagRepository",
    "TimelineBoundsSnapshot",
]
