"""Persistence repositories for canonical write access."""

from pixelpast.persistence.repositories.canonical import (
    AssetMediaRepository,
    AssetOriginalCandidate,
    AssetRepository,
    AssetThumbnailCandidate,
    AssetUpsertResult,
    EventReplaceResult,
    EventRepository,
    JobRunRepository,
    PersonRepository,
    SourceRepository,
    SourceUpsertResult,
    TagRepository,
)
from pixelpast.persistence.repositories.daily_aggregates import (
    CanonicalTimelineRepository,
    DailyAggregateRepository,
    DailyAggregateSnapshot,
    DailyViewRepository,
)
from pixelpast.persistence.repositories.manage_data import (
    MANUAL_PERSON_GROUP_TYPE,
    ManageDataPersonGroupRepository,
    ManageDataPersonRepository,
    PersonCatalogSnapshot,
    PersonGroupCatalogSnapshot,
    PersonGroupMembershipSnapshot,
)
from pixelpast.persistence.repositories.places import (
    EventPlaceLinkUpsertResult,
    GooglePlaceEventCandidateLoadResult,
    GooglePlaceEventCandidateSnapshot,
    PlaceRepository,
    PlaceUpsertResult,
)
from pixelpast.persistence.repositories.social_graph_read import (
    PersonAssetMembershipSnapshot,
    SocialGraphLinkSnapshot,
    SocialGraphPersonSnapshot,
    SocialGraphReadRepository,
    SocialGraphReadSnapshot,
)
from pixelpast.persistence.repositories.timeline_read import (
    DailyAggregateReadRepository,
    DailyAggregateReadSnapshot,
    DailyViewCatalogSnapshot,
    DayActivityItemSnapshot,
    DayMapPointSnapshot,
    DayPersonLinkSnapshot,
    DayTagLinkSnapshot,
    DayTimelineItemSnapshot,
    DayTimelineRepository,
    ExplorationReadRepository,
    TimelineBoundsSnapshot,
)

__all__ = [
    "AssetRepository",
    "AssetMediaRepository",
    "AssetOriginalCandidate",
    "AssetThumbnailCandidate",
    "AssetUpsertResult",
    "CanonicalTimelineRepository",
    "DayActivityItemSnapshot",
    "DayMapPointSnapshot",
    "DayPersonLinkSnapshot",
    "DayTagLinkSnapshot",
    "DailyViewCatalogSnapshot",
    "DailyAggregateReadRepository",
    "DailyAggregateReadSnapshot",
    "DailyAggregateRepository",
    "DailyAggregateSnapshot",
    "DailyViewRepository",
    "EventReplaceResult",
    "EventRepository",
    "DayTimelineItemSnapshot",
    "DayTimelineRepository",
    "ExplorationReadRepository",
    "JobRunRepository",
    "EventPlaceLinkUpsertResult",
    "GooglePlaceEventCandidateLoadResult",
    "GooglePlaceEventCandidateSnapshot",
    "MANUAL_PERSON_GROUP_TYPE",
    "ManageDataPersonGroupRepository",
    "ManageDataPersonRepository",
    "PersonRepository",
    "PersonCatalogSnapshot",
    "PersonGroupCatalogSnapshot",
    "PersonGroupMembershipSnapshot",
    "PlaceRepository",
    "PlaceUpsertResult",
    "PersonAssetMembershipSnapshot",
    "SocialGraphLinkSnapshot",
    "SocialGraphPersonSnapshot",
    "SocialGraphReadRepository",
    "SocialGraphReadSnapshot",
    "SourceRepository",
    "SourceUpsertResult",
    "TagRepository",
    "TimelineBoundsSnapshot",
]
